### ISSUE TITLE
ajout de post

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#1]
- lorsque ajout d'un post via l'interface > boutons à modifier pour publier + cacher les boutons wordpress
- lorsqu'on clique sur 'publier', on doit recharger la page pour afficher le post (appuyer sur rafraîchir ne change rien)
  > solution : utiliser le bouton rafraichir pour rafraichir aussi la page.

**Comment by louis-ev** [comment]
Check. Le bouton "crayon" recharge la page.

![capture d ecran 2015-03-23 a 17 33 55](https://cloud.githubusercontent.com/assets/1948417/6784971/2454abdc-d183-11e4-8dbd-e9464ef2208c.png)
