### ISSUE TITLE
ajout du nombre de vue par projet

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#14]
à afficher en dessous du titre du projet dans la page d'accueil
et dans la description de la page projet

**Comment by louis-ev** [comment]
Quelle utilité ? pour qui ? parce qu'en l'état ça va être plus décevant qu'autre chose...

**Comment by paulinegourlet** [comment]
C'est pas grave. C'est utile pour nous et c'est intéressant de voir si ça incite à poster plus régulièrement.

**Comment by louis-ev** [comment]
Je pense pas que ça incite...
Le nombre est trop faible actuellement pour que ça vaille quoi que ce soit.
