### ISSUE TITLE
Interface connexion

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#17]
- Bouton connexion non visible
- bouton s'enregister non visible
- Préciser qu'on ne peut pas rentrer de majuscules (ou plutôt préciser les symboles valables)

**Comment by louis-ev** [comment]
Ok.

Par contre pas bien compris le "Préciser qu'on ne peut pas rentrer de majuscules (ou plutôt préciser les symboles valables)"
Dans quel(s) champs ?

![capture d ecran 2015-03-22 a 20 52 43](https://cloud.githubusercontent.com/assets/1948417/6771108/6c23cf82-d0d5-11e4-918d-26d9d9e0b941.png)

**Comment by paulinegourlet** [comment]
Super.
Pour les signes: un mec de l'openlab a essayé un pseudo avec des caps et il a eu un message d'erreur.
Il faut que tout soit en minuscules. D'autres contraintes ? (espace, accent ?) le préciser qqpart ?
