### ISSUE TITLE
visualisation pdf

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#18]
Possible ?

**Comment by louis-ev** [comment]
Pas dans la page mais dans un autre onglet.
Quel est le comportement attendu ?

**Comment by paulinegourlet** [comment]
Peut-être une pré-visualisation alors du pdf ? genre la première page ? C'est possible ?
Sinon laisse tomber cet issue, c'est bien comme ça.

**Comment by louis-ev** [comment]
Euh non, pas possible.
