### ISSUE TITLE
Titre des projets

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#3]
Disparaît au scroll

> doit être visible dans la barre en haut (entre l'opendoc et le @ blabla, ça pourrait être bien cool. Possible ?) / en tout cas, visible même lorsque scroll.

**Comment by louis-ev** [comment]
Ok

![capture d ecran 2015-03-23 a 18 08 03](https://cloud.githubusercontent.com/assets/1948417/6785705/9251ac9e-d187-11e4-8a29-75e77868f1f7.png)

**Comment by paulinegourlet** [comment]
![capture d ecran 2015-03-24 a 16 26 41](https://cloud.githubusercontent.com/assets/7995654/6805337/bfc01970-d242-11e4-8c5f-9f044374f148.png)

Et comme ça ? 
- les 3 boutons à passer sur une seule ligne.
