### ISSUE TITLE
renvoi aux instances sur lopendoc.org

### ISSUE THREAD

**Issue by paulinegourlet** [sarahgarcin/lopendoc#5]
Après réflexion et vu le problème de l'url qui parfois renvoie à lopendoc.org sans /lebal ou autre, autant faire un renvoi aux différents projets sur lopendoc.org en mode grille ou liste.

**Comment by louis-ev** [comment]
Toujours d'actualité ? C'est gênant par rapport au fait que tout le monde peut s'enregistrer, non ?

**Comment by paulinegourlet** [comment]
Nan c'est pas grave. Je pense que c'est important.
Il n'y a pas tant de projets que ça (lebal, lopendoc, la friche), et les contributeurs sont peu nombreux de tte façon.

> pour le moment, il est écrit "page de tests" quand on est sur la page www.lopendoc.org
> à enlever
